// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"e572a62172c18f8351b85e74c315b357af285c57c2f17c11a5dd98cf51f740d411458a6c70fd536d08d2466ab9330f4dc5a0c98d47d2a2bebc4369167ed8504e"}}
];
